#! /bin/sh
### BEGIN INIT INFO
# Provides:          SaunaControl
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts & Stops My Programm
# Description:       Starts & Stops My Programm
### END INIT INFO
 
#Switch case fuer den ersten Parameter
case "$1" in
    start)
 #Aktion wenn start uebergeben wird
	DISPLAY=:0 /usr/bin/xinput --set-prop 'FT5406 memory based driver' 'Coordinate Transformation Matrix'  0 1 0 -1 0 1 0 0 1
        /usr/bin/saunacontrol
 
    stop)
 #Aktion wenn stop uebergeben wird
        echo "Stoppe MeinProgramm"
        ;;
 
    restart)
 #Aktion wenn restart uebergeben wird
        echo "Restarte MeinProgramm"
        ;;
 *)
 #Standard Aktion wenn start|stop|restart nicht passen
 echo "(start|stop|restart)"
 ;;
esac
 
exit 0