name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: npm install
    - name: Package
      run: npm run package
    - name: Upload to Release
      uses: JasonEtco/upload-to-release@v0.1.1

